// ══════════════════════════════════════════════════════════════════════════════
// LanguageContext.jsx — Multi-Language Support (10 Indian Regional Languages)
// ══════════════════════════════════════════════════════════════════════════════
import { createContext, useState, useEffect, useContext } from "react";

export const LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
];

export const TRANSLATIONS = {
  en: {
    // Navigation
    home: "Home",
    myProfiles: "My Profile",
    myAppointments: "My Appointments",
    allDoctors: "All Doctors",
    yourReports: "Your Reports",
    healthProfile: "Health Profile",
    giveFeedback: "Give Feedback",
    support: "Support",
    legalPage: "Legal Page",
    logout: "Log out",
    hi: "Hi",
    location: "New Delhi, India",

    // Home & Dashboard
    findDoctorHero: "Find the Perfect Doctor for",
    forYourNeeds: "Your Needs",
    medicationSchedule: "Medication Schedule",
    taken: "✓ Taken",
    pending: "Pending",
    loadMore: "Load More",
    upcomingAppointments: "Upcoming Appointments",
    noUpcomingAppointments: "No upcoming appointments",

    // Doctors Page
    findYourDoctor: "Find Your Doctor",
    searchDoctorPlaceholder: "Search doctor by name or speciality...",
    experience: "Experience",
    fee: "Fee",
    bookNow: "Book Now",
    yearsExp: "yrs exp.",
    noDoctorsFound: "No doctors found",

    // Booking
    selectDate: "Select Date",
    availableSlots: "Available Slots",
    confirmBooking: "Confirm Booking",
    proceedToPayment: "Proceed to Payment",

    // Payment
    paymentGateway: "Payment Gateway",
    orderSummary: "Order Summary",
    consultationFee: "Consultation Fee",
    serviceTax: "Service Tax",
    totalAmount: "Total Amount",
    payNow: "Pay Now",

    // Reports
    medicalReports: "Medical Reports",
    uploadReport: "Upload Report",
    viewReport: "View Report",
    noReportsFound: "No reports found",

    // Support & Feedback
    helpAndSupport: "Help & Support",
    faq: "Frequently Asked Questions",
    rateExperience: "Rate your experience",
    submitFeedback: "Submit Feedback",

    // Common Actions
    refresh: "Refresh",
    copyEhr: "Copy EHR",
    printRx: "Print Rx & Summary",
    saveAndPrint: "Save & Print Prescription",
    clearForm: "Clear Form",
    add: "Add",
    close: "Close",
    loading: "Loading...",
    themeToggle: "Toggle Theme",
    languageSelect: "Language",

    // Clinical HUD
    telemetryTitle: "Patient Telemetry & AI Clinical Review",
    token: "Token",
    paymentCleared: "Payment Cleared",
    paymentPending: "Payment Pending",
    appointmentSlot: "Appointment Slot",
    consultationDate: "Consultation Date",
    clinicalRiskMatrix: "Clinical Risk Matrix",
    labBiomarkerTriage: "Lab Biomarker Triage",
    highPriorityAlerts: "High Priority",
    normalBaseline: "Normal Baseline",
    criticalDeviations: "Critical Deviations",
    allBiomarkersNormal: "All Biomarkers Normal",
    realtimeWave: "Realtime Telemetry Wave",
    heartRate: "Heart Rate (ECG)",
    bloodPressure: "Blood Pressure",
    spO2: "SpO2 Oxygen",
    consultationActive: "Consultation Active",
    organScannerTitle: "Holographic Organ Pathology & Risk Radar",
    activeSystemicScan: "ACTIVE SYSTEMIC SCAN",
    vascularHematology: "Hematology & Vascular",
    immuneLeukocytes: "Immune & Leukocytes",
    renalFiltration: "Renal & Filtration",
    hepaticMetabolic: "Hepatic & Metabolic",
    aiDiagnosticsTab: "AI Clinical Diagnostics",
    historyTab: "Patient Medical History",
    rxTab: "Consultation & Prescription (Rx)",
    labBiomarkersTitle: "Laboratory Biomarkers & Reference Analytics",
    all: "All",
    abnormal: "Critical / Abnormal",
    normal: "Normal",
    aiInsightsTitle: "Gemini Neural Medical AI Insights",
    allergiesTitle: "Allergies & Medication Profile",
    knownAllergies: "Known Patient Allergies (High Caution)",
    noAllergies: "No Known Drug Allergies Reported",
    currentMedications: "Current Active Medications",
    verifiedBloodGroup: "Verified Blood Group",
    chronicConditions: "Chronic & Known Conditions",
    currentSymptoms: "Current Patient Symptoms",
    surgeriesHistory: "Past Surgeries & Major Illness",
    familyHistory: "Family Medical History",
    lifestyleHabits: "Lifestyle & Behavioral Factors",
    examinationDiagnosis: "Clinical Examination & Provisional Diagnosis",
    provisionalDiagnosis: "Provisional Diagnosis / Assessment",
    followUpSchedule: "Next Follow-Up Schedule",
    clinicalFindings: "Clinical Examination & Findings",
    doctorAdvice: "Doctor Advice & Dietary Guidelines",
    prescribedMedications: "Prescribed Medications (Rx)",
    medicineName: "Medicine Name & Strength",
    dosage: "Dosage",
    frequencyTiming: "Frequency / Timing",
    duration: "Duration",
    action: "Action",
  },

  hi: {
    // Navigation
    home: "होम",
    myProfiles: "मेरी प्रोफ़ाइल",
    myAppointments: "मेरे अपॉइंटमेंट्स",
    allDoctors: "सभी डॉक्टर्स",
    yourReports: "आपकी रिपोर्ट्स",
    healthProfile: "स्वास्थ्य प्रोफ़ाइल",
    giveFeedback: "प्रतिक्रिया दें",
    support: "सहायता केंद्र",
    legalPage: "नियम एवं शर्तें",
    logout: "लॉग आउट",
    hi: "नमस्ते",
    location: "नई दिल्ली, भारत",

    // Home & Dashboard
    findDoctorHero: "अपनी जरूरतों के लिए खोजें",
    forYourNeeds: "सर्वश्रेष्ठ डॉक्टर",
    medicationSchedule: "दवा समय-सारिणी",
    taken: "✓ ले ली",
    pending: "बाकी",
    loadMore: "और देखें",
    upcomingAppointments: "आगामी अपॉइंटमेंट्स",
    noUpcomingAppointments: "कोई आगामी अपॉइंटमेंट नहीं है",

    // Doctors Page
    findYourDoctor: "अपना डॉक्टर चुनें",
    searchDoctorPlaceholder: "डॉक्टर का नाम या विशेषज्ञता खोजें...",
    experience: "अनुभव",
    fee: "शुल्क",
    bookNow: "अभी बुक करें",
    yearsExp: "वर्ष अनुभव",
    noDoctorsFound: "कोई डॉक्टर नहीं मिला",

    // Booking
    selectDate: "तारीख चुनें",
    availableSlots: "उपलब्ध समय स्लॉट",
    confirmBooking: "बुकिंग कन्फर्म करें",
    proceedToPayment: "भुगतान के लिए आगे बढ़ें",

    // Payment
    paymentGateway: "पेमेंट गेटवे",
    orderSummary: "ऑर्डर विवरण",
    consultationFee: "परामर्श शुल्क",
    serviceTax: "सेवा कर (टैक्स)",
    totalAmount: "कुल राशि",
    payNow: "अभी भुगतान करें",

    // Reports
    medicalReports: "मेडिकल रिपोर्ट्स",
    uploadReport: "रिपोर्ट अपलोड करें",
    viewReport: "रिपोर्ट देखें",
    noReportsFound: "कोई रिपोर्ट उपलब्ध नहीं है",

    // Support & Feedback
    helpAndSupport: "सहायता एवं समर्थन",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    rateExperience: "अपना अनुभव साझा करें",
    submitFeedback: "प्रतिक्रिया भेजें",

    // Common Actions
    refresh: "रिफ्रेश",
    copyEhr: "EHR कॉपी करें",
    printRx: "प्रिस्क्रिप्शन प्रिंट",
    saveAndPrint: "सेव और प्रिंट प्रिस्क्रिप्शन",
    clearForm: "फॉर्म साफ करें",
    add: "जोड़ें",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    themeToggle: "थीम बदलें",
    languageSelect: "भाषा",

    // Clinical HUD
    telemetryTitle: "रोगी टेलीमेट्री और AI क्लिनिकल समीक्षा",
    token: "टोकन",
    paymentCleared: "भुगतान स्वीकृत",
    paymentPending: "भुगतान लंबित",
    appointmentSlot: "अपॉइंटमेंट समय",
    consultationDate: "परामर्श तिथि",
    clinicalRiskMatrix: "क्लिनिकल जोखिम स्थिति",
    labBiomarkerTriage: "लैब बायोमार्कर विश्लेषण",
    highPriorityAlerts: "उच्च प्राथमिकता",
    normalBaseline: "सामान्य स्थिति",
    criticalDeviations: "गंभीर विचलन",
    allBiomarkersNormal: "सभी बायोमार्कर सामान्य",
    realtimeWave: "लाइव टेलीमेट्री तरंग",
    heartRate: "हृदय गति (ECG)",
    bloodPressure: "रक्तचाप (BP)",
    spO2: "ऑक्सीजन (SpO2)",
    consultationActive: "परामर्श चालू है",
    organScannerTitle: "होलोग्राफिक अंग विकृति एवं जोखिम रडार",
    activeSystemicScan: "सक्रिय प्रणालीगत स्कैन",
    vascularHematology: "रक्त विज्ञान एवं वाहिका",
    immuneLeukocytes: "प्रतिरक्षा एवं श्वेत रक्त कोशिकाएं",
    renalFiltration: "गुर्दे एवं निस्पंदन",
    hepaticMetabolic: "यकृत (लिवर) एवं चयापचय",
    aiDiagnosticsTab: "AI क्लिनिकल डायग्नोस्टिक्स",
    historyTab: "रोगी का चिकित्सा इतिहास",
    rxTab: "परामर्श एवं प्रिस्क्रिप्शन (Rx)",
    labBiomarkersTitle: "प्रयोगशाला बायोमार्कर एवं संदर्भ विश्लेषण",
    all: "सभी",
    abnormal: "गंभीर / असामान्य",
    normal: "सामान्य",
    aiInsightsTitle: "जेमिनी न्यूरल मेडिकल AI निष्कर्ष",
    allergiesTitle: "एलर्जी एवं दवा प्रोफ़ाइल",
    knownAllergies: "ज्ञात रोगी एलर्जी (उच्च सावधानी)",
    noAllergies: "कोई ज्ञात दवा एलर्जी नहीं",
    currentMedications: "वर्तमान सक्रिय दवाएं",
    verifiedBloodGroup: "प्रमाणित रक्त समूह",
    chronicConditions: "पुरानी एवं ज्ञात बीमारियां",
    currentSymptoms: "रोगी के वर्तमान लक्षण",
    surgeriesHistory: "पूर्व सर्जरी एवं गंभीर बीमारियां",
    familyHistory: "पारिवारिक चिकित्सा इतिहास",
    lifestyleHabits: "जीवनशैली एवं आदतें",
    examinationDiagnosis: "क्लिनिकल जांच एवं अनंतिम निदान",
    provisionalDiagnosis: "अनंतिम निदान / आकलन",
    followUpSchedule: "अगली परामर्श समय-सारिणी",
    clinicalFindings: "क्लिनिकल निष्कर्ष",
    doctorAdvice: "डॉक्टर की सलाह एवं आहार निर्देश",
    prescribedMedications: "निर्धारित दवाएं (Rx)",
    medicineName: "दवा का नाम एवं मात्रा",
    dosage: "खुराक",
    frequencyTiming: "लेने का समय",
    duration: "अवधि",
    action: "कार्रवाई",
  },

  bn: {
    home: "হোম",
    myProfiles: "আমার প্রোফাইল",
    myAppointments: "আমার অ্যাপয়েন্টমেন্ট",
    allDoctors: "সমস্ত ডাক্তার",
    yourReports: "আপনার রিপোর্ট",
    healthProfile: "স্বাস্থ্য প্রোফাইল",
    giveFeedback: "মতামত দিন",
    support: "সহায়তা কেন্দ্র",
    legalPage: "আইনি তথ্য",
    logout: "লগ আউট",
    hi: "নমস্কার",
    location: "নতুন দিল্লি, ভারত",
    findDoctorHero: "আপনার প্রয়োজনের জন্য খুঁজুন",
    forYourNeeds: "সেরা ডাক্তার",
    medicationSchedule: "ঔষধের সময়সূচী",
    taken: "✓ নেওয়া হয়েছে",
    pending: "বাকি",
    loadMore: "আরো দেখুন",
    upcomingAppointments: "আসন্ন অ্যাপয়েন্টমেন্ট",
    noUpcomingAppointments: "কোন আসন্ন অ্যাপয়েন্টমেন্ট নেই",
    findYourDoctor: "ডাক্তার খুঁজুন",
    searchDoctorPlaceholder: "ডাক্তারের নাম বা বিশেষত্ব খুঁজুন...",
    experience: "অভিজ্ঞতা",
    fee: "ফি",
    bookNow: "এখনই বুক করুন",
    yearsExp: "বছরের অভিজ্ঞতা",
    noDoctorsFound: "কোন ডাক্তার পাওয়া যায়নি",
    selectDate: "তারিখ নির্বাচন করুন",
    availableSlots: "উপলব্ধ সময়",
    confirmBooking: "বুকিং নিশ্চিত করুন",
    proceedToPayment: "পেমেন্টে এগিয়ে যান",
    paymentGateway: "পেমেন্ট গেটওয়ে",
    orderSummary: "অর্ডারের বিবরণ",
    consultationFee: "পরামর্শ ফি",
    serviceTax: "ট্যাক্স",
    totalAmount: "মোট পরিমাণ",
    payNow: "এখনই পরিশোধ করুন",
    medicalReports: "মেডিকেল রিপোর্ট",
    uploadReport: "রিপোর্ট আপলোড",
    viewReport: "রিপোর্ট দেখুন",
    noReportsFound: "কোন রিপোর্ট নেই",
    helpAndSupport: "সহায়তা ও সাহায্য",
    faq: "সাধারণ জিজ্ঞাসা",
    rateExperience: "আপনার অভিজ্ঞতা জানান",
    submitFeedback: "মতামত জমা দিন",
    refresh: "রিফ্রেশ",
    copyEhr: "EHR কপি",
    printRx: "প্রেসক্রিপশন প্রিন্ট",
    saveAndPrint: "সংরক্ষণ ও প্রিন্ট",
    clearForm: "মুছুন",
    add: "যোগ করুন",
    close: "বন্ধ করুন",
    loading: "লোড হচ্ছে...",
    themeToggle: "থিম পরিবর্তন",
    languageSelect: "ভাষা",
    telemetryTitle: "রোগীর টেলিমেট্রি ও AI পর্যালোচনা",
    token: "টোকেন",
    paymentCleared: "পেমেন্ট সম্পন্ন",
    paymentPending: "পেমেন্ট বাকি",
    appointmentSlot: "সময়",
    consultationDate: "তারিখ",
    clinicalRiskMatrix: "ঝুঁকির মাত্রা",
    labBiomarkerTriage: "বায়োমার্কার বিশ্লেষণ",
    highPriorityAlerts: "উচ্চ অগ্রাধিকার",
    normalBaseline: "স্বাভাবিক",
    criticalDeviations: "সমস্যাযুক্ত",
    allBiomarkersNormal: "সব স্বাভাবিক",
    realtimeWave: "লাইভ ইসিজি",
    heartRate: "হৃদস্পন্দন (ECG)",
    bloodPressure: "রক্তচাপ (BP)",
    spO2: "অক্সিজেন (SpO2)",
    consultationActive: "পরামর্শ চলছে",
    organScannerTitle: "অঙ্গ প্যাথলজি রাডার",
    activeSystemicScan: "সক্রিয় স্ক্যান",
    vascularHematology: "রক্তবিজ্ঞান",
    immuneLeukocytes: "রোগপ্রতিরোধ",
    renalFiltration: "কিডনি",
    hepaticMetabolic: "লিভার",
    aiDiagnosticsTab: "AI ডায়াগনস্টিকস",
    historyTab: "চিকিৎসার ইতিহাস",
    rxTab: "প্রেসক্রিপশন (Rx)",
    labBiomarkersTitle: "ল্যাব বায়োমার্কার",
    all: "সব",
    abnormal: "অস্বাভাবিক",
    normal: "স্বাভাবিক",
    aiInsightsTitle: "AI ফলাফল",
    allergiesTitle: "অ্যালার্জি ও ওষুধ",
    knownAllergies: "জ্ঞাত অ্যালার্জি",
    noAllergies: "কোন অ্যালার্জি নেই",
    currentMedications: "বর্তমান ওষুধ",
    verifiedBloodGroup: "রক্তের গ্রুপ",
    chronicConditions: "দীর্ঘস্থায়ী রোগ",
    currentSymptoms: "বর্তমান লক্ষণ",
    surgeriesHistory: "অতীত সার্জারি",
    familyHistory: "পারিবারিক ইতিহাস",
    lifestyleHabits: "জীবনধারা",
    examinationDiagnosis: "পরীক্ষা ও রোগ নির্ণয়",
    provisionalDiagnosis: "প্রাথমিক নির্ণয়",
    followUpSchedule: "পরবর্তী ভিজিট",
    clinicalFindings: "ক্লিনিকাল ফলাফল",
    doctorAdvice: "ডাক্তারের পরামর্শ",
    prescribedMedications: "নির্ধারিত ওষুধ (Rx)",
    medicineName: "ওষুধের নাম",
    dosage: "মাত্রা",
    frequencyTiming: "সময়",
    duration: "মেয়াদ",
    action: "পদক্ষেপ",
  },

  te: {
    home: "హోమ్",
    myProfiles: "నా ప్రొఫైల్",
    myAppointments: "నా అపాయింట్‌మెంట్లు",
    allDoctors: "వైద్యులందరూ",
    yourReports: "మీ నివేదికలు",
    healthProfile: "ఆరోగ్య ప్రొఫైల్",
    giveFeedback: "అభిప్రాయం ఇవ్వండి",
    support: "సహాయ కేంద్రం",
    legalPage: "చట్టపరమైన సమాచారం",
    logout: "లాగ్ అవుట్",
    hi: "నమస్కారం",
    location: "న్యూ ఢిల్లీ, భారతదేశం",
    findDoctorHero: "మీ అవసరాలకు సరైన",
    forYourNeeds: "వైద్యుడిని ఎంచుకోండి",
    medicationSchedule: "మందుల సమయ పట్టిక",
    taken: "✓ తీసుకున్నారు",
    pending: "మిగిలి ఉంది",
    loadMore: "మరిన్ని చూడండి",
    upcomingAppointments: "రాబోయే అపాయింట్‌మెంట్లు",
    noUpcomingAppointments: "రాబోయే అపాయింట్‌మెంట్లు లేవు",
    findYourDoctor: "వైద్యుడిని వెతకండి",
    searchDoctorPlaceholder: "పేరు లేదా స్పెషాలిటీ ద్వారా వెతకండి...",
    experience: "అనుభవం",
    fee: "ఫీజు",
    bookNow: "ఇప్పుడే బుక్ చేయండి",
    yearsExp: "సంవత్సరాల అనుభవం",
    noDoctorsFound: "వైద్యులు దొరకలేదు",
    selectDate: "తేదీని ఎంచుకోండి",
    availableSlots: "అందుబాటులో ఉన్న సమయాలు",
    confirmBooking: "బుకింగ్ నిర్ధారించండి",
    proceedToPayment: "చెల్లింపునకు వెళ్లండి",
    paymentGateway: "పేమెంట్ గేట్‌వే",
    orderSummary: "ఆర్డర్ వివరాలు",
    consultationFee: "సంప్రదింపు ఫీజు",
    serviceTax: "సర్వీస్ ట్యాక్స్",
    totalAmount: "మొత్తం మొత్తం",
    payNow: "ఇప్పుడే చెల్లించండి",
    medicalReports: "వైద్య నివేదికలు",
    uploadReport: "నివేదికను అప్‌లోడ్ చేయండి",
    viewReport: "నివేదికను వీక్షించండి",
    noReportsFound: "నివేదికలు లేవు",
    helpAndSupport: "సహాయం & మద్దతు",
    faq: "తరచుగా అడిగే ప్రశ్నలు",
    rateExperience: "మీ అనుభవాన్ని తెలియజేయండి",
    submitFeedback: "అభిప్రాయాన్ని పంపండి",
    refresh: "రిఫ్రెష్",
    copyEhr: "EHR కాపీ చేయండి",
    printRx: "ప్రిస్క్రిప్షన్ ప్రింట్",
    saveAndPrint: "సేవ్ & ప్రింట్",
    clearForm: "ఫారమ్ క్లియర్ చేయండి",
    add: "జోడించండి",
    close: "మూసివేయండి",
    loading: "లోడ్ అవుతోంది...",
    themeToggle: "థీమ్ మార్చండి",
    languageSelect: "భాష",
    telemetryTitle: "రోగి టెలిమెట్రీ & AI క్లినికల్ సమీక్ష",
    token: "టోకెన్",
    paymentCleared: "చెల్లింపు పూర్తయింది",
    paymentPending: "చెల్లింపు బాకీ",
    appointmentSlot: "సమయం",
    consultationDate: "తేదీ",
    clinicalRiskMatrix: "ప్రమాద స్థితి",
    labBiomarkerTriage: "బయోమార్కర్ విశ్లేషణ",
    highPriorityAlerts: "అత్యవసరం",
    normalBaseline: "సాధారణం",
    criticalDeviations: "సమస్యలు",
    allBiomarkersNormal: "అన్నీ సాధారణం",
    realtimeWave: "లైవ్ ECG తరంగం",
    heartRate: "గుండె వేగం (ECG)",
    bloodPressure: "రక్తపోటు (BP)",
    spO2: "ఆక్సిజన్ (SpO2)",
    consultationActive: "సంప్రదింపు కొనసాగుతోంది",
    organScannerTitle: "అవయవాల స్కాన్ & రాడార్",
    activeSystemicScan: "యాక్టివ్ స్కాన్",
    vascularHematology: "రక్త వ్యవస్థ",
    immuneLeukocytes: "రోగనిరోధక శక్తి",
    renalFiltration: "మూత్రపిండాలు",
    hepaticMetabolic: "కాలేయం",
    aiDiagnosticsTab: "AI డయాగ్నోస్టిక్స్",
    historyTab: "వైద్య చరిత్ర",
    rxTab: "ప్రిస్క్రిప్షన్ (Rx)",
    labBiomarkersTitle: "ల్యాబ్ విశ్లేషణ",
    all: "అన్నీ",
    abnormal: "అసాధారణం",
    normal: "సాధారణం",
    aiInsightsTitle: "AI సలహాలు",
    allergiesTitle: "అలర్జీలు & మందులు",
    knownAllergies: "తెలిసిన అలర్జీలు",
    noAllergies: "అలర్జీలు లేవు",
    currentMedications: "ప్రస్తుత మందులు",
    verifiedBloodGroup: "రక్త గ్రూపు",
    chronicConditions: "దీర్ఘకాలిక సమస్యలు",
    currentSymptoms: "ప్రస్తుత లక్షణాలు",
    surgeriesHistory: "గత శస్త్రచికిత్సలు",
    familyHistory: "కుటుంబ చరిత్ర",
    lifestyleHabits: "జీవనశైలి",
    examinationDiagnosis: "పరీక్ష & నిర్ధారణ",
    provisionalDiagnosis: "ప్రాథమిక నిర్ధారణ",
    followUpSchedule: "తదుపరి సందర్శన",
    clinicalFindings: "క్లినికల్ ఫలితాలు",
    doctorAdvice: "వైద్యుల సలహా",
    prescribedMedications: "సూచించిన మందులు (Rx)",
    medicineName: "మందు పేరు",
    dosage: "మోతాదు",
    frequencyTiming: "సమయం",
    duration: "వ్యవధి",
    action: "చర్య",
  },

  mr: {
    home: "मुख्यपृष्ठ",
    myProfiles: "माझे प्रोफाइल",
    myAppointments: "माझ्या भेटी",
    allDoctors: "सर्व डॉक्टर",
    yourReports: "तुमचे अहवाल",
    healthProfile: "आरोग्य प्रोफाइल",
    giveFeedback: "प्रतिक्रिया द्या",
    support: "मदत केंद्र",
    legalPage: "कायदेशीर माहिती",
    logout: "लॉग आउट",
    hi: "नमस्कार",
    location: "नवी दिल्ली, भारत",
    findDoctorHero: "तुमच्या गरजांनुसार शोधा",
    forYourNeeds: "सर्वोत्तम डॉक्टर",
    medicationSchedule: "औषधांचे वेळापत्रक",
    taken: "✓ घेतले",
    pending: "बाकी",
    loadMore: "अधिक पहा",
    upcomingAppointments: "आगामी भेटी",
    noUpcomingAppointments: "कोणत्याही आगामी भेटी नाहीत",
    findYourDoctor: "डॉक्टर निवडा",
    searchDoctorPlaceholder: "नाव किंवा तज्ज्ञतेनुसार शोधा...",
    experience: "अनुभव",
    fee: "फी",
    bookNow: "आता बुक करा",
    yearsExp: "वर्षे अनुभव",
    noDoctorsFound: "डॉक्टर सापडले नाहीत",
    selectDate: "तारीख निवडा",
    availableSlots: "उपलब्ध वेळ",
    confirmBooking: "बुकिंग निश्चित करा",
    proceedToPayment: "पेमेंटकडे जा",
    paymentGateway: "पेमेंट गेटवे",
    orderSummary: "ऑर्डर तपशील",
    consultationFee: "सल्ला फी",
    serviceTax: "सेवा कर",
    totalAmount: "एकूण रक्कम",
    payNow: "आता पैसे द्या",
    medicalReports: "वैद्यकीय अहवाल",
    uploadReport: "अहवाल अपलोड करा",
    viewReport: "अहवाल पहा",
    noReportsFound: "कोणताही अहवाल उपलब्ध नाही",
    helpAndSupport: "मदत आणि पाठबळ",
    faq: "वारंवार विचारले जाणारे प्रश्न",
    rateExperience: "तुमचा अनुभव सांगा",
    submitFeedback: "प्रतिक्रिया पाठवा",
    refresh: "रिफ्रेश",
    copyEhr: "EHR कॉपी करा",
    printRx: "प्रिस्क्रिप्शन प्रिंट करा",
    saveAndPrint: "जतन करा आणि प्रिंट करा",
    clearForm: "फॉर्म साफ करा",
    add: "जोडा",
    close: "बंद करा",
    loading: "लोड होत आहे...",
    themeToggle: "थीम बदला",
    languageSelect: "भाषा",
    telemetryTitle: "रुग्ण टेलीमेट्री आणि AI विश्लेषण",
    token: "टोकन",
    paymentCleared: "पेमेंट पूर्ण",
    paymentPending: "पेमेंट बाकी",
    appointmentSlot: "वेळ",
    consultationDate: "तारीख",
    clinicalRiskMatrix: "जोखीम पातळी",
    labBiomarkerTriage: "लॅब बायोमार्कर",
    highPriorityAlerts: "उच्च प्राधान्य",
    normalBaseline: "सामान्य",
    criticalDeviations: "गंभीर समस्या",
    allBiomarkersNormal: "सर्व सामान्य",
    realtimeWave: "थेट ईसीजी तरंग",
    heartRate: "हृदयाचे ठोके (ECG)",
    bloodPressure: "रक्तदाब (BP)",
    spO2: "ऑक्सिजन (SpO2)",
    consultationActive: "सल्ला सुरू आहे",
    organScannerTitle: "अवयव स्कॅन रडार",
    activeSystemicScan: "सक्रिय स्कॅन",
    vascularHematology: "रक्तवाहिन्या",
    immuneLeukocytes: "प्रतिकारशक्ती",
    renalFiltration: "मूत्रपिंड",
    hepaticMetabolic: "यकृत",
    aiDiagnosticsTab: "AI डायग्नोस्टिक्स",
    historyTab: "वैद्यकीय इतिहास",
    rxTab: "प्रिस्क्रिप्शन (Rx)",
    labBiomarkersTitle: "लॅब चाचण्या",
    all: "सर्व",
    abnormal: "असामान्य",
    normal: "सामान्य",
    aiInsightsTitle: "AI निष्कर्ष",
    allergiesTitle: "अलर्जी आणि औषधे",
    knownAllergies: "माहित असलेल्या अलर्जी",
    noAllergies: "कोणतीही अलर्जी नाही",
    currentMedications: "चालू औषधे",
    verifiedBloodGroup: "रक्तगट",
    chronicConditions: "दीर्घकालीन आजार",
    currentSymptoms: "सध्याची लक्षणे",
    surgeriesHistory: "मागील शस्त्रक्रिया",
    familyHistory: "कौटुंबिक इतिहास",
    lifestyleHabits: "जीवनशैली",
    examinationDiagnosis: "तपासणी आणि निदान",
    provisionalDiagnosis: "प्राथमिक निदान",
    followUpSchedule: "पुढील भेट",
    clinicalFindings: "वैद्यकीय निरीक्षणे",
    doctorAdvice: "डॉक्टरांचा सल्ला",
    prescribedMedications: "दिलेली औषधे (Rx)",
    medicineName: "औषधाचे नाव",
    dosage: "डोस",
    frequencyTiming: "वेळ",
    duration: "कालावधी",
    action: "कृती",
  },

  ta: {
    home: "முகப்பு",
    myProfiles: "என் சுயவிவரம்",
    myAppointments: "என் முன்பதிவுகள்",
    allDoctors: "அனைத்து மருத்துவர்கள்",
    yourReports: "உங்கள் அறிக்கைகள்",
    healthProfile: "சுகாதார விவரம்",
    giveFeedback: "கருத்து தெரிவிக்கவும்",
    support: "உதவி மையம்",
    legalPage: "சட்ட தகவல்",
    logout: "வெளியேறு",
    hi: "வணக்கம்",
    location: "புது தில்லி, இந்தியா",
    findDoctorHero: "உங்கள் தேவைக்கேற்ற",
    forYourNeeds: "சிறந்த மருத்துவர்",
    medicationSchedule: "மருந்து அட்டவணை",
    taken: "✓ எடுக்கப்பட்டது",
    pending: "மீதமுள்ளது",
    loadMore: "மேலும் பார்க்க",
    upcomingAppointments: "வரவிருக்கும் முன்பதிவுகள்",
    noUpcomingAppointments: "முன்பதிவுகள் ஏதுமில்லை",
    findYourDoctor: "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
    searchDoctorPlaceholder: "பெயர் அல்லது சிறப்பு மூலம் தேடவும்...",
    experience: "அனுபவம்",
    fee: "கட்டணம்",
    bookNow: "இப்போதே பதிவு செய்",
    yearsExp: "ஆண்டுகள் அனுபவம்",
    noDoctorsFound: "மருத்துவர்கள் காணப்படவில்லை",
    selectDate: "தேதியைத் தேர்ந்தெடுக்கவும்",
    availableSlots: "கிடைக்கும் நேரங்கள்",
    confirmBooking: "பதிவை உறுதிப்படுத்தவும்",
    proceedToPayment: "கட்டணத்திற்கு செல்லவும்",
    paymentGateway: "பணம் செலுத்தும் தளம்",
    orderSummary: "விவரங்கள்",
    consultationFee: "ஆலோசனை கட்டணம்",
    serviceTax: "சேவை வரி",
    totalAmount: "மொத்த தொகை",
    payNow: "இப்போது செலுத்தவும்",
    medicalReports: "மருத்துவ அறிக்கைகள்",
    uploadReport: "அறிக்கையை பதிவேற்றவும்",
    viewReport: "அறிக்கையை பார்க்கவும்",
    noReportsFound: "அறிக்கைகள் இல்லை",
    helpAndSupport: "உதவி & ஆதரவு",
    faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    rateExperience: "உங்கள் அனுபவத்தை பகிரவும்",
    submitFeedback: "கருத்து சமர்ப்பிக்கவும்",
    refresh: "புதுப்பி",
    copyEhr: "EHR நகலெடு",
    printRx: "பரிந்துரை அச்சிடு",
    saveAndPrint: "சேமித்து அச்சிடு",
    clearForm: "அழி",
    add: "சேர்",
    close: "மூடு",
    loading: "ஏற்றப்படுகிறது...",
    themeToggle: "தீம் மாற்று",
    languageSelect: "மொழி",
    telemetryTitle: "நோயாளி டெலிமெட்ரி & AI மதிப்பாய்வு",
    token: "டோக்கன்",
    paymentCleared: "கட்டணம் செலுத்தப்பட்டது",
    paymentPending: "கட்டணம் நிலுவையில் உள்ளது",
    appointmentSlot: "நேரம்",
    consultationDate: "தேதி",
    clinicalRiskMatrix: "ஆபத்து நிலை",
    labBiomarkerTriage: "ஆய்வக பகுப்பாய்வு",
    highPriorityAlerts: "அவசரம்",
    normalBaseline: "சாதாரணம்",
    criticalDeviations: "சிக்கல்கள்",
    allBiomarkersNormal: "அனைத்தும் சாதாரணம்",
    realtimeWave: "நேரலை ECG அலை",
    heartRate: "இதய துடிப்பு (ECG)",
    bloodPressure: "இரத்த அழுத்தம் (BP)",
    spO2: "ஆக்ஸிஜன் (SpO2)",
    consultationActive: "ஆலோசனை நடக்கிறது",
    organScannerTitle: "உறுப்பு ஸ்கேன் ரேடார்",
    activeSystemicScan: "செயலில் உள்ள ஸ்கேன்",
    vascularHematology: "இரத்த அமைப்பு",
    immuneLeukocytes: "நோய் எதிர்ப்பு சக்தி",
    renalFiltration: "சிறுநீரகம்",
    hepaticMetabolic: "கல்லீரல்",
    aiDiagnosticsTab: "AI பரிசோதனை",
    historyTab: "மருத்துவ வரலாறு",
    rxTab: "மருத்துவ சீட்டு (Rx)",
    labBiomarkersTitle: "ஆய்வக குறியீடுகள்",
    all: "அனைத்தும்",
    abnormal: "மாறுபட்டவை",
    normal: "சாதாரணம்",
    aiInsightsTitle: "AI கணிப்புகள்",
    allergiesTitle: "ஒவ்வாமை & மருந்துகள்",
    knownAllergies: "அறியப்பட்ட ஒவ்வாமைகள்",
    noAllergies: "ஒவ்வாமை இல்லை",
    currentMedications: "தற்போதைய மருந்துகள்",
    verifiedBloodGroup: "இரத்த வகை",
    chronicConditions: "நீண்டகால நோய்கள்",
    currentSymptoms: "தற்போதைய அறிகுறிகள்",
    surgeriesHistory: "கடந்தகால அறுவை சிகிச்சைகள்",
    familyHistory: "குடும்ப வரலாறு",
    lifestyleHabits: "வாழ்க்கை முறை",
    examinationDiagnosis: "பரிசோதனை & கண்டறிதல்",
    provisionalDiagnosis: "ஆரம்ப கண்டறிதல்",
    followUpSchedule: "அடுத்த வருகை",
    clinicalFindings: "மருத்துவ அவதானிப்புகள்",
    doctorAdvice: "மருத்துவர் ஆலோசனை",
    prescribedMedications: "பரிந்துரைக்கப்பட்ட மருந்துகள் (Rx)",
    medicineName: "மருந்து பெயர்",
    dosage: "அளவு",
    frequencyTiming: "நேரம்",
    duration: "காலம்",
    action: "செயல்",
  },

  gu: {
    home: "હોમ",
    myProfiles: "મારી પ્રોફાઇલ",
    myAppointments: "મારી મુલાકાતો",
    allDoctors: "બધા ડૉક્ટર્સ",
    yourReports: "તમારા રિપોર્ટ્સ",
    healthProfile: "આરોગ્ય પ્રોફાઇલ",
    giveFeedback: "પ્રતિસાદ આપો",
    support: "સહાયતા કેન્દ્ર",
    legalPage: "કાનૂની માહિતી",
    logout: "લૉગ આઉટ",
    hi: "નમસ્તે",
    location: "નવી દિલ્હી, ભારત",
    findDoctorHero: "તમારી જરૂરિયાતો માટે શોધો",
    forYourNeeds: "શ્રેષ્ઠ ડૉક્ટર",
    medicationSchedule: "દવાઓનું સમયપત્રક",
    taken: "✓ લીધી",
    pending: "બાકી",
    loadMore: "વધુ જુઓ",
    upcomingAppointments: "આગામી મુલાકાતો",
    noUpcomingAppointments: "કોઈ આગામી મુલાકાત નથી",
    findYourDoctor: "ડૉક્ટર પસંદ કરો",
    searchDoctorPlaceholder: "નામ અથવા વિશેષતા દ્વારા શોધો...",
    experience: "અનુભવ",
    fee: "ફી",
    bookNow: "હમણાં બુક કરો",
    yearsExp: "વર્ષનો અનુભવ",
    noDoctorsFound: "કોઈ ડૉક્ટર મળ્યા નથી",
    selectDate: "તારીખ પસંદ કરો",
    availableSlots: "ઉપલબ્ધ સમય",
    confirmBooking: "બુકિંગ કન્ફર્મ કરો",
    proceedToPayment: "ચુકવણી તરફ આગળ વધો",
    paymentGateway: "પેમેન્ટ ગેટવે",
    orderSummary: "ઓર્ડર વિગતો",
    consultationFee: "કન્સલ્ટેશન ફી",
    serviceTax: "સર્વિસ ટેક્સ",
    totalAmount: "કુલ રકમ",
    payNow: "હમણાં ચૂકવો",
    medicalReports: "મેડિકલ રિપોર્ટ્સ",
    uploadReport: "રિપોર્ટ અપલોડ કરો",
    viewReport: "રિપોર્ટ જુઓ",
    noReportsFound: "કોઈ રિપોર્ટ નથી",
    helpAndSupport: "મદદ અને સપોર્ટ",
    faq: "વારંવાર પૂછાતા પ્રશ્નો",
    rateExperience: "તમારો અનુભવ જણાવો",
    submitFeedback: "પ્રતિસાદ સબમિટ કરો",
    refresh: "રિફ્રેશ",
    copyEhr: "EHR કૉપિ કરો",
    printRx: "પ્રિસ્ક્રિપ્શન પ્રિન્ટ",
    saveAndPrint: "સાચવો અને પ્રિન્ટ કરો",
    clearForm: "સાફ કરો",
    add: "ઉમેરો",
    close: "બંધ કરો",
    loading: "લોડ થઈ રહ્યું છે...",
    themeToggle: "થીમ બદલો",
    languageSelect: "ભાષા",
    telemetryTitle: "દર્દી ટેલિમેટ્રી અને AI સમીક્ષા",
    token: "ટોકન",
    paymentCleared: "ચુકવણી થઈ ગઈ",
    paymentPending: "ચુકવણી બાકી",
    appointmentSlot: "સમય",
    consultationDate: "તારીખ",
    clinicalRiskMatrix: "જોખમ સ્તર",
    labBiomarkerTriage: "લેબ વિશ્લેષણ",
    highPriorityAlerts: "ઉચ્ચ પ્રાથમિકતા",
    normalBaseline: "સામાન્ય",
    criticalDeviations: "ગંભીર સમસ્યાઓ",
    allBiomarkersNormal: "બધું સામાન્ય છે",
    realtimeWave: "લાઈવ ECG તરંગ",
    heartRate: "હૃદયના ધબકારા (ECG)",
    bloodPressure: "બ્લડ પ્રેશર (BP)",
    spO2: "ઓક્સિજન (SpO2)",
    consultationActive: "પરામર્શ ચાલુ છે",
    organScannerTitle: "અંગ સ્કેન રડાર",
    activeSystemicScan: "સક્રિય સ્કેન",
    vascularHematology: "રક્ત પ્રણાલી",
    immuneLeukocytes: "રોગપ્રતિકારક શક્તિ",
    renalFiltration: "કિડની",
    hepaticMetabolic: "લિવર",
    aiDiagnosticsTab: "AI ડાયગ્નોસ્ટિક્સ",
    historyTab: "મેડિકલ ઇતિહાસ",
    rxTab: "પ્રિસ્ક્રિપ્શન (Rx)",
    labBiomarkersTitle: "લેબ બાયોમાર્કર્સ",
    all: "બધા",
    abnormal: "અસામાન્ય",
    normal: "સામાન્ય",
    aiInsightsTitle: "AI તારણો",
    allergiesTitle: "એલર્જી અને દવાઓ",
    knownAllergies: "જાણીતી એલર્જી",
    noAllergies: "કોઈ એલર્જી નથી",
    currentMedications: "ચાલુ દવાઓ",
    verifiedBloodGroup: "બ્લડ ગ્રુપ",
    chronicConditions: "લાંબા ગાળાના રોગો",
    currentSymptoms: "હાલના લક્ષણો",
    surgeriesHistory: "ભૂતકાળની સર્જરી",
    familyHistory: "પારિવારિક ઇતિહાસ",
    lifestyleHabits: "જીવનશૈલી",
    examinationDiagnosis: "તપાસ અને નિદાન",
    provisionalDiagnosis: "પ્રાથમિક નિદાન",
    followUpSchedule: "આગામી મુલાકાત",
    clinicalFindings: "ક્લિનિકલ તારણો",
    doctorAdvice: "ડૉક્ટરની સલાહ",
    prescribedMedications: "લખેલી દવાઓ (Rx)",
    medicineName: "દવાનું નામ",
    dosage: "ડોઝ",
    frequencyTiming: "સમય",
    duration: "સમયગાળો",
    action: "ક્રિયા",
  },

  kn: {
    home: "ಮುಖಪುಟ",
    myProfiles: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    myAppointments: "ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
    allDoctors: "ಎಲ್ಲಾ ವೈದ್ಯರು",
    yourReports: "ನಿಮ್ಮ ವರದಿಗಳು",
    healthProfile: "ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್",
    giveFeedback: "ಅಭಿಪ್ರಾಯ ತಿಳಿಸಿ",
    support: "ಸಹಾಯ ಕೇಂದ್ರ",
    legalPage: "ಕಾನೂನು ಮಾಹಿತಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    hi: "ನಮಸ್ಕಾರ",
    location: "ನವದೆಹಲಿ, ಭಾರತ",
    findDoctorHero: "ನಿಮ್ಮ ಅಗತ್ಯಕ್ಕೆ ತಕ್ಕಂತೆ",
    forYourNeeds: "ಉತ್ತಮ ವೈದ್ಯರು",
    medicationSchedule: "ಔಷಧಿ ವೇಳಾಪಟ್ಟಿ",
    taken: "✓ ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ",
    pending: "ಬಾಕಿ ಇದೆ",
    loadMore: "ಇನ್ನಷ್ಟು ನೋಡಿ",
    upcomingAppointments: "ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
    noUpcomingAppointments: "ಯಾವುದೇ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ",
    findYourDoctor: "ವೈದ್ಯರನ್ನು ಹುಡುಕಿ",
    searchDoctorPlaceholder: "ಹೆಸರು ಅಥವಾ ತಜ್ಞತೆಯಿಂದ ಹುಡುಕಿ...",
    experience: "ಅನುಭವ",
    fee: "ಶುಲ್ಕ",
    bookNow: "ಈಗಲೇ ಬುಕ್ ಮಾಡಿ",
    yearsExp: "ವರ್ಷಗಳ ಅನುಭವ",
    noDoctorsFound: "ವೈದ್ಯರು ಕಂಡುಬಂದಿಲ್ಲ",
    selectDate: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    availableSlots: "ಲಭ್ಯವಿರುವ ಸಮಯ",
    confirmBooking: "ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ",
    proceedToPayment: "ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    paymentGateway: "ಪಾವತಿ ಗೇಟ್‌ವೇ",
    orderSummary: "ವಿವರಗಳು",
    consultationFee: "ಸಮಾಲೋಚನೆ ಶುಲ್ಕ",
    serviceTax: "ಸೇವಾ ತೆರಿಗೆ",
    totalAmount: "ಒಟ್ಟು ಮೊತ್ತ",
    payNow: "ಈಗಲೇ ಪಾವತಿಸಿ",
    medicalReports: "ವೈದ್ಯಕೀಯ ವರದಿಗಳು",
    uploadReport: "ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    viewReport: "ವರದಿ ವೀಕ್ಷಿಸಿ",
    noReportsFound: "ವರದಿಗಳು ಲಭ್ಯವಿಲ್ಲ",
    helpAndSupport: "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
    faq: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    rateExperience: "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ",
    submitFeedback: "ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ",
    refresh: "ರಿಫ್ರೆಶ್",
    copyEhr: "EHR ನಕಲಿಸಿ",
    printRx: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಪ್ರಿಂಟ್",
    saveAndPrint: "ಉಳಿಸಿ ಮತ್ತು ಪ್ರಿಂಟ್ ಮಾಡಿ",
    clearForm: "ತೆರವುಗೊಳಿಸಿ",
    add: "ಸೇರಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    themeToggle: "ಥೀಮ್ ಬದಲಿಸಿ",
    languageSelect: "ಭಾಷೆ",
    telemetryTitle: "ರೋಗಿ ಟೆಲಿಮೆಟ್ರಿ ಮತ್ತು AI ಪರಿಶೀಲನೆ",
    token: "ಟೋಕನ್",
    paymentCleared: "ಪಾವತಿ ಪೂರ್ಣಗೊಂಡಿದೆ",
    paymentPending: "ಪಾವತಿ ಬಾಕಿ",
    appointmentSlot: "ಸಮಯ",
    consultationDate: "ದಿನಾಂಕ",
    clinicalRiskMatrix: "ಅಪಾಯದ ಮಟ್ಟ",
    labBiomarkerTriage: "ಲ್ಯಾಬ್ ವಿಶ್ಲೇಷಣೆ",
    highPriorityAlerts: "ತುರ್ತು",
    normalBaseline: "ಸಾಮಾನ್ಯ",
    criticalDeviations: "ಸಮಸ್ಯೆಗಳು",
    allBiomarkersNormal: "ಎಲ್ಲವೂ ಸಾಮಾನ್ಯವಾಗಿದೆ",
    realtimeWave: "ಲೈವ್ ECG ತರಂಗ",
    heartRate: "ಹೃದಯ ಬಡಿತ (ECG)",
    bloodPressure: "ರಕ್ತದೊತ್ತಡ (BP)",
    spO2: "ಆಮ್ಲಜನಕ (SpO2)",
    consultationActive: "ಸಮಾಲೋಚನೆ ನಡೆಯುತ್ತಿದೆ",
    organScannerTitle: "ಅಂಗಾಂಗ ಸ್ಕ್ಯಾನ್ ರೇಡಾರ್",
    activeSystemicScan: "ಸಕ್ರಿಯ ಸ್ಕ್ಯಾನ್",
    vascularHematology: "ರಕ್ತ ಪರಿಚಲನೆ",
    immuneLeukocytes: "ರೋಗನಿರೋಧಕ ಶಕ್ತಿ",
    renalFiltration: "ಮೂತ್ರಪಿಂಡ",
    hepaticMetabolic: "ಯಕೃತ್ತು",
    aiDiagnosticsTab: "AI ರೋಗನಿರ್ಣಯ",
    historyTab: "ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ",
    rxTab: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ (Rx)",
    labBiomarkersTitle: "ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳು",
    all: "ಎಲ್ಲಾ",
    abnormal: "ಅಸಹಜ",
    normal: "ಸಾಮಾನ್ಯ",
    aiInsightsTitle: "AI ಫಲಿತಾಂಶಗಳು",
    allergiesTitle: "ಅಲರ್ಜಿ ಮತ್ತು ಔಷಧಗಳು",
    knownAllergies: "ತಿಳಿದಿರುವ ಅಲರ್ಜಿಗಳು",
    noAllergies: "ಯಾವುದೇ ಅಲರ್ಜಿ ಇಲ್ಲ",
    currentMedications: "ಪ್ರಸ್ತುತ ಔಷಧಗಳು",
    verifiedBloodGroup: "ರಕ್ತದ ಗುಂಪು",
    chronicConditions: "ದೀರ್ಘಕಾಲದ ಕಾಯಿಲೆಗಳು",
    currentSymptoms: "ಪ್ರಸ್ತುತ ಲಕ್ಷಣಗಳು",
    surgeriesHistory: "ಹಿಂದಿನ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗಳು",
    familyHistory: "ಕುಟುಂಬದ ಇತಿಹಾಸ",
    lifestyleHabits: "ಜೀವನಶೈಲಿ",
    examinationDiagnosis: "ಪರೀಕ್ಷೆ ಮತ್ತು ರೋಗನಿರ್ಣಯ",
    provisionalDiagnosis: "ಪ್ರಾಥಮಿಕ ರೋಗನಿರ್ಣಯ",
    followUpSchedule: "ಮುಂದಿನ ಭೇಟಿ",
    clinicalFindings: "ವೈದ್ಯಕೀಯ ವೀಕ್ಷಣೆಗಳು",
    doctorAdvice: "ವೈದ್ಯರ ಸಲಹೆ",
    prescribedMedications: "ಸೂಚಿಸಲಾದ ಔಷಧಗಳು (Rx)",
    medicineName: "ಔಷಧದ ಹೆಸರು",
    dosage: "ಪ್ರಮಾಣ",
    frequencyTiming: "ಸಮಯ",
    duration: "ಅವಧಿ",
    action: "ಕ್ರಮ",
  },

  ml: {
    home: "ഹോം",
    myProfiles: "എന്റെ പ്രൊഫൈൽ",
    myAppointments: "എന്റെ അപ്പോയിന്റ്മെന്റുകൾ",
    allDoctors: "എല്ലാ ഡോക്ടർമാരും",
    yourReports: "നിങ്ങളുടെ റിപ്പോർട്ടുകൾ",
    healthProfile: "ആരോഗ്യ പ്രൊഫൈൽ",
    giveFeedback: "അഭിപ്രായം അറിയിക്കുക",
    support: "സഹായ കേന്ദ്രം",
    legalPage: "നിയമപരമായ വിവരങ്ങൾ",
    logout: "ലോഗ് ഔട്ട്",
    hi: "നമസ്കാരം",
    location: "ന്യൂഡൽഹി, ഇന്ത്യ",
    findDoctorHero: "നിങ്ങളുടെ ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ",
    forYourNeeds: "മികച്ച ഡോക്ടർ",
    medicationSchedule: "മരുന്ന് സമയക്രമം",
    taken: "✓ കഴിച്ചു",
    pending: "ബാക്കി",
    loadMore: "കൂടുതൽ കാണുക",
    upcomingAppointments: "വരാനിരിക്കുന്ന അപ്പോയിന്റ്മെന്റുകൾ",
    noUpcomingAppointments: "അപ്പോയിന്റ്മെന്റുകൾ ലഭ്യമല്ല",
    findYourDoctor: "ഡോക്ടറെ കണ്ടെത്തുക",
    searchDoctorPlaceholder: "പേര് അല്ലെങ്കിൽ സ്പെഷ്യാലിറ്റി വഴി തിരയുക...",
    experience: "പരിചയം",
    fee: "ഫീസ്",
    bookNow: "ഇപ്പോൾ ബുക്ക് ചെയ്യുക",
    yearsExp: "വർഷത്തെ പരിചയം",
    noDoctorsFound: "ഡോക്ടർമാരെ കണ്ടെത്താനായില്ല",
    selectDate: "തീയതി തിരഞ്ഞെടുക്കുക",
    availableSlots: "ലഭ്യമായ സമയം",
    confirmBooking: "ബുക്കിംഗ് സ്ഥിരീകരിക്കുക",
    proceedToPayment: "പേയ്‌മെന്റിലേക്ക് പോകുക",
    paymentGateway: "പേയ്‌മെന്റ് ഗേറ്റ്‌വേ",
    orderSummary: "വിശദാംശങ്ങൾ",
    consultationFee: "കൺസൾട്ടേഷൻ ഫീസ്",
    serviceTax: "സേവന നികുതി",
    totalAmount: "ആകെ തുക",
    payNow: "ഇപ്പോൾ നൽകുക",
    medicalReports: "മെഡിക്കൽ റിപ്പോർട്ടുകൾ",
    uploadReport: "റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക",
    viewReport: "റിപ്പോർട്ട് കാണുക",
    noReportsFound: "റിപ്പോർട്ടുകൾ ലഭ്യമല്ല",
    helpAndSupport: "സഹായവും പിന്തുണയും",
    faq: "പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ",
    rateExperience: "നിങ്ങളുടെ അനുഭവം പങ്കുവെക്കുക",
    submitFeedback: "അഭിപ്രായം അയക്കുക",
    refresh: "പുതുക്കുക",
    copyEhr: "EHR പകർത്തുക",
    printRx: "പ്രിസ്ക്രിപ്ഷൻ പ്രിന്റ് ചെയ്യുക",
    saveAndPrint: "സംരക്ഷിച്ച് പ്രിന്റ് ചെയ്യുക",
    clearForm: "മായ്ക്കുക",
    add: "ചേർക്കുക",
    close: "അടയ്ക്കുക",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    themeToggle: "തീം മാറ്റുക",
    languageSelect: "ഭാഷ",
    telemetryTitle: "രോഗി ടെലിമെട്രി & AI അവലോകനം",
    token: "ടോക്കൺ",
    paymentCleared: "പേയ്‌മെന്റ് പൂർത്തിയായി",
    paymentPending: "പേയ്‌മെന്റ് ബാക്കി",
    appointmentSlot: "സമയം",
    consultationDate: "തീയതി",
    clinicalRiskMatrix: "അപകടസാധ്യത നില",
    labBiomarkerTriage: "ലാബ് പരിശോധന",
    highPriorityAlerts: "അടിയന്തിരം",
    normalBaseline: "സാധാരണം",
    criticalDeviations: "പ്രശ്നങ്ങൾ",
    allBiomarkersNormal: "എല്ലാം സാധാരണമാണ്",
    realtimeWave: "തത്സമയ ECG തരംഗം",
    heartRate: "ഹൃദയമിടിപ്പ് (ECG)",
    bloodPressure: "രക്തസമ്മർദ്ദം (BP)",
    spO2: "ഓക്സിജൻ (SpO2)",
    consultationActive: "കൺസൾട്ടേഷൻ നടക്കുന്നു",
    organScannerTitle: "അവയവ സ്കാൻ റഡാർ",
    activeSystemicScan: "ആക്ടീവ് സ്കാൻ",
    vascularHematology: "രക്തചംക്രമണം",
    immuneLeukocytes: "രോഗപ്രതിരോധശേഷി",
    renalFiltration: "വൃക്കകൾ",
    hepaticMetabolic: "കരൾ",
    aiDiagnosticsTab: "AI ഡയഗ്നോസ്റ്റിക്സ്",
    historyTab: "ചികിത്സാ ചരിത്രം",
    rxTab: "പ്രിസ്ക്രിപ്ഷൻ (Rx)",
    labBiomarkersTitle: "ലാബ് പരിശോധനകൾ",
    all: "എല്ലാം",
    abnormal: "അസ്വാഭാവികം",
    normal: "സാധാരണം",
    aiInsightsTitle: "AI വിവരങ്ങൾ",
    allergiesTitle: "അലർജികളും മരുന്നുകളും",
    knownAllergies: "അലർജികൾ",
    noAllergies: "അലർജികളില്ല",
    currentMedications: "നിലവിലെ മരുന്നുകൾ",
    verifiedBloodGroup: "രക്തഗ്രൂപ്പ്",
    chronicConditions: "ദീർഘകാല രോഗങ്ങൾ",
    currentSymptoms: "ലക്ഷണങ്ങൾ",
    surgeriesHistory: "മുൻകാല ശസ്ത്രക്രിയകൾ",
    familyHistory: "കുടുംബ ചരിത്രം",
    lifestyleHabits: "ജീവിതശൈലി",
    examinationDiagnosis: "പരിശോധനയും രോഗനിർണയവും",
    provisionalDiagnosis: "പ്രാഥമിക രോഗനിർണയം",
    followUpSchedule: "അടുത്ത സന്ദർശനം",
    clinicalFindings: "ക്ലിനിക്കൽ കണ്ടെത്തലുകൾ",
    doctorAdvice: "ഡോക്ടറുടെ ഉപദേശം",
    prescribedMedications: "നിർദ്ദേശിച്ച മരുന്നുകൾ (Rx)",
    medicineName: "മരുന്നിന്റെ പേര്",
    dosage: "അളവ്",
    frequencyTiming: "സമയം",
    duration: "കാലാവധി",
    action: "നടപടി",
  },

  pa: {
    home: "ਮੁੱਖ ਪੰਨਾ",
    myProfiles: "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
    myAppointments: "ਮੇਰੀਆਂ ਮੁਲਾਕਾਤਾਂ",
    allDoctors: "ਸਾਰੇ ਡਾਕਟਰ",
    yourReports: "ਤੁਹਾਡੀਆਂ ਰਿਪੋਰਟਾਂ",
    healthProfile: "ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ",
    giveFeedback: "ਫੀਡਬੈਕ ਦਿਓ",
    support: "ਸਹਾਇਤਾ ਕੇਂਦਰ",
    legalPage: "ਕਾਨੂੰਨੀ ਜਾਣਕਾਰੀ",
    logout: "ਲਾਗ ਆਉਟ",
    hi: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    location: "ਨਵੀਂ ਦਿੱਲੀ, ਭਾਰਤ",
    findDoctorHero: "ਆਪਣੀ ਲੋੜ ਅਨੁਸਾਰ ਚੁਣੋ",
    forYourNeeds: "ਸਭ ਤੋਂ ਵਧੀਆ ਡਾਕਟਰ",
    medicationSchedule: "ਦਵਾਈਆਂ ਦਾ ਸਮਾਂ-ਸਾਰਣੀ",
    taken: "✓ ਲੈ ਲਈ",
    pending: "ਬਾਕੀ",
    loadMore: "ਹੋਰ ਦੇਖੋ",
    upcomingAppointments: "ਆਉਣ ਵਾਲੀਆਂ ਮੁਲਾਕਾਤਾਂ",
    noUpcomingAppointments: "ਕੋਈ ਮੁਲਾਕਾਤ ਨਹੀਂ ਹੈ",
    findYourDoctor: "ਡਾਕਟਰ ਲੱਭੋ",
    searchDoctorPlaceholder: "ਨਾਮ ਜਾਂ ਮੁਹਾਰਤ ਨਾਲ ਖੋਜੋ...",
    experience: "ਤਜਰਬਾ",
    fee: "ਫੀਸ",
    bookNow: "ਹੁਣੇ ਬੁੱਕ ਕਰੋ",
    yearsExp: "ਸਾਲਾਂ ਦਾ ਤਜਰਬਾ",
    noDoctorsFound: "ਕੋਈ ਡਾਕਟਰ ਨਹੀਂ ਮਿਲਿਆ",
    selectDate: "ਮਿਤੀ ਚੁਣੋ",
    availableSlots: "ਉਪਲਬਧ ਸਮਾਂ",
    confirmBooking: "ਬੁਕਿੰਗ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    proceedToPayment: "ਭੁਗਤਾਨ ਵੱਲ ਵਧੋ",
    paymentGateway: "ਪੇਮੈਂਟ ਗੇਟਵੇ",
    orderSummary: "ਵੇਰਵੇ",
    consultationFee: "ਸਲਾਹ ਫੀਸ",
    serviceTax: "ਸਰਵਿਸ ਟੈਕਸ",
    totalAmount: "ਕੁੱਲ ਰਕਮ",
    payNow: "ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ",
    medicalReports: "ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ",
    uploadReport: "ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ",
    viewReport: "ਰਿਪੋਰਟ ਦੇਖੋ",
    noReportsFound: "ਕੋਈ ਰਿਪੋਰਟ ਨਹੀਂ ਹੈ",
    helpAndSupport: "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",
    faq: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ",
    rateExperience: "ਆਪਣਾ ਅਨੁਭਵ ਸਾਂਝਾ ਕਰੋ",
    submitFeedback: "ਫੀਡਬੈਕ ਭੇਜੋ",
    refresh: "ਤਾਜ਼ਾ ਕਰੋ (ਰਿਫ੍ਰੈਸ਼)",
    copyEhr: "EHR ਕਾਪੀ ਕਰੋ",
    printRx: "ਪਰਚੀ ਪ੍ਰਿੰਟ ਕਰੋ",
    saveAndPrint: "ਸੰਭਾਲੋ ਅਤੇ ਪ੍ਰਿੰਟ ਕਰੋ",
    clearForm: "ਫਾਰਮ ਸਾਫ਼ ਕਰੋ",
    add: "ਜੋੜੋ",
    close: "ਬੰਦ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    themeToggle: "ਥੀਮ ਬਦਲੋ",
    languageSelect: "ਭਾਸ਼ਾ",
    telemetryTitle: "ਮਰੀਜ਼ ਟੈਲੀਮੈਟਰੀ ਅਤੇ AI ਕਲੀਨਿਕਲ ਸਮੀਖਿਆ",
    token: "ਟੋਕਨ",
    paymentCleared: "ਭੁਗਤਾਨ ਹੋ ਗਿਆ",
    paymentPending: "ਭੁਗਤਾਨ ਬਾਕੀ",
    appointmentSlot: "ਮੁਲਾਕਾਤ ਦਾ ਸਮਾਂ",
    consultationDate: "ਸਲਾਹ-ਮਸ਼ਵਰੇ ਦੀ ਮਿਤੀ",
    clinicalRiskMatrix: "ਜੋਖਮ ਪੱਧਰ",
    labBiomarkerTriage: "ਲੈਬ ਬਾਇਓਮਾਰਕਰ ਵਿਸ਼ਲੇਸ਼ਣ",
    highPriorityAlerts: "ਉੱਚ ਤਰਜੀਹ",
    normalBaseline: "ਆਮ ਸਥਿਤੀ",
    criticalDeviations: "ਗੰਭੀਰ ਸਮੱਸਿਆਵਾਂ",
    allBiomarkersNormal: "ਸਭ ਆਮ ਹੈ",
    realtimeWave: "ਲਾਈਵ ECG ਤਰੰਗ",
    heartRate: "ਦਿਲ ਦੀ ਧੜਕਣ (ECG)",
    bloodPressure: "ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ (BP)",
    spO2: "ਆਕਸੀਜਨ (SpO2)",
    consultationActive: "ਸਲਾਹ-ਮਸ਼ਵਰਾ ਚੱਲ ਰਿਹਾ ਹੈ",
    organScannerTitle: "ਅੰਗ ਪੈਥੋਲੋਜੀ ਅਤੇ ਜੋਖਮ ਰਡਾਰ",
    activeSystemicScan: "ਸਰਗਰਮ ਸਕੈਨ",
    vascularHematology: "ਖੂਨ ਸੰਚਾਰ",
    immuneLeukocytes: "ਰੋਗ ਪ੍ਰਤੀਰੋਧਕ ਸ਼ਕਤੀ",
    renalFiltration: "ਗੁਰਦੇ (ਕਿਡਨੀ)",
    hepaticMetabolic: "ਜਿਗਰ (ਲਿਵਰ)",
    aiDiagnosticsTab: "AI ਕਲੀਨਿਕਲ ਡਾਇਗਨੌਸਟਿਕਸ",
    historyTab: "ਮੈਡੀਕਲ ਇਤਿਹਾਸ",
    rxTab: "ਨੁਸਖ਼ਾ / ਪਰਚੀ (Rx)",
    labBiomarkersTitle: "ਲੈਬ ਬਾਇਓਮਾਰਕਰਜ਼",
    all: "ਸਾਰੇ",
    abnormal: "ਅਸਧਾਰਨ",
    normal: "ਆਮ",
    aiInsightsTitle: "AI ਮੈਡੀਕਲ ਸਿੱਟੇ",
    allergiesTitle: "ਐਲਰਜੀ ਅਤੇ ਦਵਾਈਆਂ",
    knownAllergies: "ਜਾਣੀਆਂ ਐਲਰਜੀਆਂ",
    noAllergies: "ਕੋਈ ਐਲਰਜੀ ਨਹੀਂ",
    currentMedications: "ਮੌਜੂਦਾ ਦਵਾਈਆਂ",
    verifiedBloodGroup: "ਬਲੱਡ ਗਰੁੱਪ",
    chronicConditions: "ਪੁਰਾਣੀਆਂ ਬਿਮਾਰੀਆਂ",
    currentSymptoms: "ਮੌਜੂਦਾ ਲੱਛਣ",
    surgeriesHistory: "ਪਿਛਲੀਆਂ ਸਰਜਰੀਆਂ",
    familyHistory: "ਪਰਿਵਾਰਕ ਇਤਿਹਾਸ",
    lifestyleHabits: "ਜੀਵਨ ਸ਼ੈਲੀ",
    examinationDiagnosis: "ਜਾਂਚ ਅਤੇ ਸ਼ੁਰੂਆਤੀ ਨਿਦਾਨ",
    provisionalDiagnosis: "ਸ਼ੁਰੂਆਤੀ ਨਿਦਾਨ",
    followUpSchedule: "ਅਗਲੀ ਮੁਲਾਕਾਤ",
    clinicalFindings: "ਕਲੀਨਿਕਲ ਨਿਰੀਖਣ",
    doctorAdvice: "ਡਾਕਟਰ ਦੀ ਸਲਾਹ",
    prescribedMedications: "ਲਿਖੀਆਂ ਗਈਆਂ ਦਵਾਈਆਂ (Rx)",
    medicineName: "ਦਵਾਈ ਦਾ ਨਾਮ",
    dosage: "ਖੁਰਾਕ",
    frequencyTiming: "ਲੈਣ ਦਾ ਸਮਾਂ",
    duration: "ਸਮਾਂ ਸੀਮਾ",
    action: "ਕਾਰਵਾਈ",
  },
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("sih_kiosk_lang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("sih_kiosk_lang", language);
  }, [language]);

  const t = (key, fallback = "") => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (currentDict && currentDict[key]) {
      return currentDict[key];
    }
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const currentLangObj = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languages: LANGUAGES,
        currentLangObj,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
